channels:
  - conda-forge
dependencies:
  - brian2
  - ipykernel
  - matplotlib
  - seaborn
  - numpy=1.24
  - pandas<2.0
  - scipy
  - networkx
  - pyarrow
  - xlsxwriter
  - openpyxl
  - joblib
  - jupytext
  - jupyterlab
